name: 🚀 Deploy to GH Pages

# on:
#   push:
#     branches:
#       - main
on: pull_request

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    env:
      USE_SSH: true
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: |
          git config --global user.name ${{ secrets.GH_USER }}
          git config --global user.email ${{ secrets.GH_EMAIL }}
          npm install
          npm run deploy
